### ISSUE TITLE
Don't choke on missing database.yml

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rails#10]
Setup should be simply skipped with a warning that there's no config file

**Comment by aflatter** [comment]
I guess in the preparation phase (before initializers run) we'd just not define a default repository. If initializers don't configure a repository at all, we should skip setup and warn. That way, you don't get a warning if you use neither AR nor rom-sql, but something else. How does that sound?

**Comment by solnic** [comment]
Yes that sounds correct
