### ISSUE TITLE
Feedback on ROM - Rails setup

### ISSUE THREAD

**Issue by nonsenseless** [rom-rb/rom-rails#108]
I'd like to work with y'all on preparing some kind of quickstart guide for setting up ROM. I'm working my way through trying to setup a bare bones rails project to use ROM and trying to piece together the exact steps I need to follow to get a very basic configuration going is *excruciatingly* painful. I don't mind doing legwork or anything, but it shouldn't be quite such a pain in the ass to figure out what needs to be done and where.

As just one example, on the associations page, you've got this line:

`rom = ROM.container(:memory) do |config|
  config.register_relation(Users, Tasks)
end`

Where is this meant to go in a rails application? In the initializer script? It's not at all obvious from the context of the example.

Other examples would include the fact that nowhere in the Rails setup chapter do you explicitly mention that you need to swap out 'require rails/all' for each of the railties, omitting ActiveRecord or that you need to include both rom-rails and rom-sql, or that you need to explicitly set DATABASE_URLs as environment variables.

I really love the concept behind ROM and I'd love to use it on a project, but there needs to be some kind of documentation that takes you quickly through the process of scaffolding up a project.

**Comment by bryszard** [comment]
I was just about to create a PR with the fix for link to the setup guide and I've noticed that somebody already created such fix in February. Just a reminder :).

**Comment by cflipse** [comment]
(guide's been updated with file location indications.  closing)
