### ISSUE TITLE
undefined local variable or method `rom' for #<TasksController:0x007fc6b0684bc8>

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom-rails#12]
This works fine:
```ruby
class TasksController < ApplicationController
  def index
    render json: rom.read(:tasks).all
  end
end
```

This blows up:

```ruby
class TasksController < ActionController::Base
  def index
    render json: rom.read(:tasks).all
  end
end
```

This is because the ```ControllerExtension``` is included in ```ApplicationController``` and not ```ActionController::Base```. 

Some documentation where this ```rom``` method is coming from and how you can get one in your own controller base class would be nice.

**Comment by kwando** [comment]
Btw, the way to make it work is to include ```ROM::Rails::ControllerExtension``` in your controller like this:
```ruby
class TasksController < ActionController::Base
  include ROM::Rails::ControllerExtension
  def index
    render json: rom.read(:tasks).all
  end
end
```

**Comment by solnic** [comment]
Thanks for spotting this. It probably explains why you need to reload spring in the second step of rails tutorial. I will fix/improve it.

**Comment by solnic** [comment]
Fixed via [this commit](https://github.com/rom-rb/rom-rails/commit/c16e93b31071b3d909be4627c2726fe30ed92b9e)
