### ISSUE TITLE
Auto-generated commands use the same validator in Rails Form objects

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rails#42]
_From @solnic on July 20, 2015 13:13_

Which results in problems like [this question on SO](http://stackoverflow.com/questions/31505336/rom-rb-form-validation-when-using-multiple-relations)

_Copied from original issue: rom-rb/rom#290_

**Comment by solnic** [comment]
@cflipse are you planning to tackle this?

**Comment by cflipse** [comment]
Maybe?   I think that it's pretty heavily affected by whatever the plans are in rom-rb/rom#299

Basic solution seems to be that the form object has multiple validators, for each relation / command used, right?  But, something's going to have to merge the messages so they display cleanly when passed back into the form helpers ...

**Comment by solnic** [comment]
@cflipse I was thinking about NOT setting validators on commands at all. Just have a validator object orchestrated by the form, sth like:

``` ruby
def save(*args)
  validator.call(attributes)
  commit!(*args)
rescue ValidationError => e
  @errors = e.errors
end
```

**Comment by cflipse** [comment]
got it.  Makes a lot more sense this way

**Comment by cflipse** [comment]
WIP above addresses the only-validating-in-form case, although I _think_ that if there's a validation in an injected command, this will let the ValidationError bleed through.  That might be okay, if the goal is to push towards getting validations in the form.

**Comment by cflipse** [comment]
This has been "accounted" for by the deprecation of command validations as discussed above.  Closing
