### ISSUE TITLE
Documentation or Example of Configuration Without database.yml

### ISSUE THREAD

**Issue by ylg** [rom-rb/rom-rails#49]
The only information I could find for configuring a SQL gateway was by examining the files generated by Rake tasks in the Rails tutorial. Unfortunately, those files use an approach that depends on a database.yml file.

For situations where database.yml isn't the best solution, how can we configure this?

Note: I took a few stables at placing ROM.setup in a few different spots, but it seems the railtie isn't having any of that nonsense.

**Comment by solnic** [comment]
You need to use an initializer:

```
# config/initializers/rom.rb
ROM::Rails::Railtie.configure do |config|
  config.gateways[:default] = [:sql, ENV.fetch('DATABASE_URL')]
end
```

We need to add a rails guide and describe this. Thanks for reporting the issue.

**Comment by ylg** [comment]
That works a treat, thanks.
