### ISSUE TITLE
 Relations not auto loading

### ISSUE THREAD

**Issue by tesserakt** [rom-rb/rom-rails#58]
I created a new Rails 4.2.4 app and configured it according to the directions. The Sqlite connection in my rom initializer works as running a db:migrate works. The app when in the console will not autoload relations. With a user class like this in app/relations/users.rb:

```
class Users < ROM::Relation[:sql]
  # some methods
  dataset :users
  register_as :users
end
```

In the console if I type
```ruby
ROM.container
 => #<ROM::Container gateways={} relations=#<ROM::RelationRegistry elements={}> mappers=#<ROM::Registry elements={}> commands=#<ROM::Registry elements={}>>
```

Then I see that the relations are empty.

**Comment by cflipse** [comment]
Can you link to a repo with the app?

**Comment by janjiss** [comment]
Can confirm the same problem with latest master and 0.7.0 with rails version 4.2.6. I don't have an app that I can share, but I can demonstrate it on a Skype/Hangout call if that can help in any way.

**Comment by janjiss** [comment]
Okay, just created app that should demonstrate that: https://github.com/janjiss/rom_test

**Comment by janjiss** [comment]
@tesserakt Please use ```ROM::Rails::Railtie.container``` to access it. There is an error in docs. The fix should be there soon. @cflipse I think this can be closed?

**Comment by tesserakt** [comment]
Great; please close it as soon as the docs are updated. And thanks again!

**Comment by cflipse** [comment]
Docs updated, closing this now.

Apologies for the confusion
