### ISSUE TITLE
Rake db:reset is not working because of multiple connections

### ISSUE THREAD

**Issue by janjiss** [rom-rb/rom-rails#65]
Hey, I am using ROM in conjunction with AR and when I try to do rake db:reset, ROM has an active connection and disallows to drop the database. 

rake db:reset
PG::ObjectInUse: ERROR:  database "makeweight_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "makeweight_development"

**Comment by solnic** [comment]
@janjiss override `rake db:reset` and do `ROM.env.disconnect` as a workaround

**Comment by janjiss** [comment]
@solnic Thanks!

**Comment by janjiss** [comment]
For future references and to help others, this is what the solution looks like:
```ruby
task :remove_rom_connection => [:environment] do
  ROM.env.disconnect
end

Rake::Task["db:reset"].clear_prerequisites()
Rake::Task["db:reset"].enhance [:remove_rom_connection, "db:drop", "db:setup"]
```

**Comment by solnic** [comment]
@janjiss it would be nice to extend rails tutorial with this information, many people might be trying out ROM next to AR so this is gonna be crucial

**Comment by janjiss** [comment]
@solnic Can I create a section "Running alongside active record" ? There are few things that need to be done for it to work properly:
1) Frozen schema issue (Monkey patch for development until the issue is solved)
```
if Rails.env.development?
  module ROM
    class Schema
      def finalize!(gateway = nil, &block)
        @attributes = inferrer.call(name.dataset, gateway) if inferrer
        @primary_key = select { |attr| attr.meta[:primary_key] == true }
        block.call if block
      end
    end
  end
end
```
2) Rake db:migrate issue, where the the schema throws an error. That is monkey patch as well
```
module ROM
  module Rails
    class Railtie < ::Rails::Railtie
      alias_method :create_container!, :create_container
      def create_container
        begin
          create_container!
        rescue => e
          puts "Container failed to initialize because of #{e.inspect}"
          puts "This message comes from the monkey patch in #{__FILE__}, if you are using rake, then this is fine"
        end
      end
    end
  end
end
```
3) db:reset task from above

The first one is not a critical issue, but it still happens on every request after any file is being saved, which is kind of annoying. These monkey patches make me cringe, but ATM I don't see other way. Thoughts?

**Comment by janjiss** [comment]
@solnic I think this can be closed and continued on documentation section?
