### ISSUE TITLE
Remove virtus dependency

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-rails#69]
virtus is used in one place, `ROM::Rails::Configuration` ... we should be able to update that to one of the DRY gems and remove the virtus runtime dependency

**Comment by bilby91** [comment]
I can work a PR on this.

**Comment by cflipse** [comment]
Sounds good.

On reflection, I don't think it's particularly necessary to chase down anything from Dry anyway.  A basic, normal object for the configs should work fine.  Or, if one really wants to go that way, there are Configuration classes in ActiveSupport that I'd be fine with using _in a rails gem_ (ie, don't expect to be able to use that within the rest of ROM ;) )

**Comment by bilby91** [comment]
@cflipse Did not know about that class. Will take a look at it and use it in the refactor.

**Comment by cflipse** [comment]
It's well buried. ;)

**Comment by cflipse** [comment]
closed in #72
